FROM docker.m.daocloud.io/library/golang:1.26-alpine AS builder

WORKDIR /app

COPY logger/ logger/
COPY proctor/ proctor/

WORKDIR /app/proctor

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/controller ./cmd/controller
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/proctor ./cmd/proctor

FROM docker.m.daocloud.io/library/alpine:3.22 AS controller

RUN apk add --no-cache ca-certificates

WORKDIR /app

COPY --from=builder /out/controller /app/controller

EXPOSE 8081

ENTRYPOINT ["/app/controller"]

FROM docker.m.daocloud.io/library/alpine:3.22 AS proctor

RUN apk add --no-cache ca-certificates

WORKDIR /app

COPY --from=builder /out/proctor /app/proctor

EXPOSE 9090

ENTRYPOINT ["/app/proctor"]
